data:
  path: csvs/vehicles.csv
  upload_limit: 10.0
dealer:
  license_id: 475
  url: https://www.canadasmotors.ca
listing:
  description:
    replace:
      new_value: null
      old_value: null
  lifetime: 8.0
  public_groups: "\u0423\u043A\u0440\u0430\u0457\u043D\u0446\u0456 \u2758 \u0422\u043E\
    \u0440\u043E\u043D\u0442\u043E, \u041A\u0430\u043D\u0430\u0434\u0430 (Ukrainians\
    \ \u2758 Toronto, Ontario, Canada);\U0001F1FA\U0001F1E6\U0001F1E8\U0001F1E6\u0422\
    \u043E\u0440\u043E\u043D\u0442\u043E \u0415\u0442\u043E\u0431\u0456\u043A\u043E\
    \ \u0412\u0437\u0430\u0454\u043C\u043D\u0430 \u0414\u043E\u043F\u043E\u043C\u043E\
    \u0433\u0430\u263A\uFE0F\U0001F1E8\U0001F1E6\U0001F1FA\U0001F1E6"
log:
  system:
    file_path: logs/system.log
  user:
    file_path: logs/user.log
photos:
  base_folder: /Users/i.kaliuzhnyi/PycharmProjects/facebook-marketplace-auto-dealership-bot/photos
scraper:
  action_random_delay:
    max: 3.2
    min: 0.29
  listing_random_delay:
    max: 3600
    min: 600
  schedule:
    crontab: 0 8-20 * * 1-5
