data:
  path: csvs/vehicles.csv
  upload_limit: 10.0
dealer:
  license_id: 475
  url: https://www.canadasmotors.ca
listing:
  lifetime: 8.0
  description:
    replace:
      old_value:
      new_value:
log:
  system:
    file_path: logs/system.log
  user:
    file_path: logs/user.log
photos:
  base_folder: photos
scraper:
  action_random_delay:
    max: 7.2
    min: 0.29
  listing_random_delay:
    max: 3600
    min: 600
  schedule:
    crontab: 0 8-20 * * 1-5
